build: false

environment:
  matrix:
    - PYTHON: "C:\\Python26"
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - "%PYTHON%/Scripts/pip.exe install -e ."
  - "%PYTHON%/Scripts/pip.exe install -r requirements-test.txt"

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/http.exe --debug"
  - "%PYTHON%/Scripts/py.test.exe"
