version: "#{build}"

build: false

branches:
  only:
    - master

environment:
  matrix:
    # click doesn't work on Python 2.6 and Windows
    # - PYTHON: "C:\\Python26"
    - PYTHON: "C:\\Python27"
    # pytest does not support Python 3.3
    # - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - "%PYTHON%/Scripts/pip.exe install -e ."
  - "%PYTHON%/Scripts/pip.exe install -r requirements-test.txt"

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/http.exe --debug"
  - "%PYTHON%/Scripts/pytest.exe"
